development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mail_development
  pool: 5
  username: root
  password: "'"
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mail_test
  pool: 5
  username: root
  password: "'"

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mail_production
  pool: 5
  username: root
  password: "'"
